### ISSUE TITLE
I just want to use to_html no code, please tell me how to install it.

### ISSUE THREAD

**Issue by qianxuanyon** [timkpaine/jupyterlab_commands#15]
The html no code is not displayed after the plugin is installed.

![image](https://user-images.githubusercontent.com/29041881/68083544-c661e580-fe64-11e9-8611-dca2f2d78b8c.png)
![image](https://user-images.githubusercontent.com/29041881/68083553-e691a480-fe64-11e9-8b66-f517e7ad34e4.png)
![image](https://user-images.githubusercontent.com/29041881/68083565-0923bd80-fe65-11e9-8deb-aa6d55d4a530.png)

**Comment by timkpaine** [comment]
https://github.com/timkpaine/jupyterlab_nbconvert_nocode
