### ISSUE TITLE
Command not showing in command palette.

### ISSUE THREAD

**Issue by smejak** [timkpaine/jupyterlab_commands#83]
**Describe the bug**
Hello. I have created a new conda environment
```
conda create -n jlab-test -c conda-forge jupyter-packaging nodejs notebook ipykernel jupyterlab python=3.8
```
and went through the installation as described in the README.

Then I ran `jupyter notebook --generate-config` and added the example code to the generated `jupyter_notebook_config.py`. When I tried running jupyter lab, the console logged a message saying the jupyterlab_commands extension was loaded, but the example command was not shown in the command palette.

Do you know what might be the issue?

**Expected behavior**
The python function in the `jupyter_notebook_config.py` should be shown in the command palette.

**Desktop (please complete the following information):**
 - OS: macOS 12.3
 - Browser: Brave
 - jupyterlab: 3.4.4

**Comment by timkpaine** [comment]
did you enable the server extension?

**Comment by timkpaine** [comment]
closing as out of date, please open a new issue if the problem persists
